In [1]:
!pip install tensorflow==2.1.0

In [6]:
import tensorflow as tf
from tensorflow import keras
import os
import cv2
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.utils import to_categorical
from numpy import argmax

In [7]:
x=np.zeros((183,96,96,3),dtype=np.float32)
ye=np.zeros((183,1),dtype=np.float32)

In [25]:
p=0
for filename in os.listdir('./players'):
    #if it's a not hidden directory
    if(filename.startswith('.') == False):
        for player in os.listdir('./players'+'/'+filename):
            if(player.startswith('.') == False):
                
                img=cv2.imread('./players'+'/'+filename+'/'+player)
                try: 
                    x[p]=cv2.resize(img,(96,96))
                    ye[p]=int(filename)
                    p=p+1
                except:
                    print('Error resizing: ' + './players'+'/'+filename+'/'+ player)
                
y = to_categorical(ye)
#print(y)   

Error resizing: ./players/2/32.jpg
Error resizing: ./players/2/2020-11-22_083023.jpg
Error resizing: ./players/2/2020-11-22_142251.jpg
Error resizing: ./players/2/2020-11-22_142047.jpg
Error resizing: ./players/2/2020-11-22_082935.jpg
Error resizing: ./players/2/2020-11-22_083008.jpg
Error resizing: ./players/2/2020-11-22_082825.jpg
Error resizing: ./players/2/2020-11-22_083332.jpg
Error resizing: ./players/2/2020-11-22_082945.jpg
Error resizing: ./players/2/2020-11-22_142143.jpg
Error resizing: ./players/2/2020-11-22_142153.jpg
Error resizing: ./players/2/2020-11-22_142224.jpg
Error resizing: ./players/2/2020-11-22_082612.jpg
Error resizing: ./players/2/45.jpg
Error resizing: ./players/2/2020-11-22_083321.jpg
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1.

In [26]:
x=x/255.0

In [27]:
from sklearn.utils import shuffle

In [28]:
v, u = shuffle(x, y)

In [29]:
inputs=keras.layers.Input((96,96,3))
l1=keras.layers.Conv2D(32,kernel_size=(3,3),activation='relu')(inputs)
l2=keras.layers.MaxPool2D((2,2))(l1)


l3=keras.layers.Conv2D(16,(3,3),activation='relu')(l2)
l4=keras.layers.MaxPool2D((2,2))(l3)

l5=keras.layers.Conv2D(8,(3,3),activation='relu')(l4)
l6=keras.layers.MaxPool2D((2,2))(l5)

l7=keras.layers.Conv2D(2,(3,3),activation='relu')(l6)


l8=keras.layers.Flatten()(l7)
l9=keras.layers.Dense(256,activation='relu')(l8)
l10=keras.layers.Dropout(0.5)(l9)
l11=keras.layers.Dense(3,activation='sigmoid')(l10)
model=keras.Model(inputs=inputs,outputs=l11)

In [30]:
model.compile(loss='binary_crossentropy', 
              optimizer='rmsprop', 
              metrics=['accuracy'])

In [31]:
model.fit(v,u,6,500)

Train on 183 samples
Epoch 1/500
183/183 [==============================] - 2s 9ms/sample - loss: 0.6293 - accuracy: 0.6430
Epoch 2/500
183/183 [==============================] - 1s 4ms/sample - loss: 0.5152 - accuracy: 0.6831
Epoch 3/500
183/183 [==============================] - 1s 4ms/sample - loss: 0.3972 - accuracy: 0.7942
Epoch 4/500
183/183 [==============================] - 1s 5ms/sample - loss: 0.2764 - accuracy: 0.8834
Epoch 5/500
183/183 [==============================] - 1s 4ms/sample - loss: 0.2163 - accuracy: 0.8980
Epoch 6/500
183/183 [==============================] - 1s 5ms/sample - loss: 0.1570 - accuracy: 0.9271
Epoch 7/500
183/183 [==============================] - 1s 4ms/sample - loss: 0.1576 - accuracy: 0.9490
Epoch 8/500
183/183 [==============================] - 1s 5ms/sample - loss: 0.1195 - accuracy: 0.9563
Epoch 9/500
183/183 [==============================] - 1s 4ms/sample - loss: 0.0949 - accuracy: 0.9690
Epoch 10/500
183/183 [==============================

183/183 [==============================] - 1s 5ms/sample - loss: 1.1866e-07 - accuracy: 1.0000
Epoch 154/500
183/183 [==============================] - 1s 4ms/sample - loss: 8.8040e-09 - accuracy: 1.0000
Epoch 155/500
183/183 [==============================] - 1s 5ms/sample - loss: 2.3998e-11 - accuracy: 1.0000
Epoch 156/500
183/183 [==============================] - 1s 4ms/sample - loss: 1.2315e-07 - accuracy: 1.0000
Epoch 157/500
183/183 [==============================] - 1s 5ms/sample - loss: 1.1518e-08 - accuracy: 1.0000
Epoch 158/500
183/183 [==============================] - 1s 5ms/sample - loss: 7.6419e-05 - accuracy: 1.0000
Epoch 159/500
183/183 [==============================] - 1s 5ms/sample - loss: 7.4731e-08 - accuracy: 1.0000
Epoch 160/500
183/183 [==============================] - 1s 5ms/sample - loss: 2.7012e-10 - accuracy: 1.0000
Epoch 161/500
183/183 [==============================] - 1s 5ms/sample - loss: 5.1286e-11 - accuracy: 1.0000
Epoch 162/500
183/183 [==========

183/183 [==============================] - 1s 4ms/sample - loss: 1.5659e-15 - accuracy: 1.0000
Epoch 304/500
183/183 [==============================] - 1s 4ms/sample - loss: 6.3107e-11 - accuracy: 1.0000
Epoch 305/500
183/183 [==============================] - 1s 4ms/sample - loss: 9.5683e-17 - accuracy: 1.0000
Epoch 306/500
183/183 [==============================] - 1s 4ms/sample - loss: 7.9869e-18 - accuracy: 1.0000
Epoch 307/500
183/183 [==============================] - 1s 4ms/sample - loss: 6.1864e-16 - accuracy: 1.0000
Epoch 308/500
183/183 [==============================] - 1s 4ms/sample - loss: 7.0414e-14 - accuracy: 1.0000
Epoch 309/500
183/183 [==============================] - 1s 4ms/sample - loss: 1.3915e-15 - accuracy: 1.0000
Epoch 310/500
183/183 [==============================] - 1s 4ms/sample - loss: 2.1319e-15 - accuracy: 1.0000
Epoch 311/500
183/183 [==============================] - 1s 4ms/sample - loss: 3.0609e-15 - accuracy: 1.0000
Epoch 312/500
183/183 [==========

183/183 [==============================] - 1s 4ms/sample - loss: 1.5421e-15 - accuracy: 1.0000
Epoch 454/500
183/183 [==============================] - 1s 4ms/sample - loss: 2.4884e-13 - accuracy: 1.0000
Epoch 455/500
183/183 [==============================] - 1s 4ms/sample - loss: 9.5829e-15 - accuracy: 1.0000
Epoch 456/500
183/183 [==============================] - 1s 4ms/sample - loss: 2.4276e-12 - accuracy: 1.0000
Epoch 457/500
183/183 [==============================] - 1s 4ms/sample - loss: 5.2563e-16 - accuracy: 1.0000
Epoch 458/500
183/183 [==============================] - 1s 4ms/sample - loss: 6.2678e-15 - accuracy: 1.0000
Epoch 459/500
183/183 [==============================] - 1s 4ms/sample - loss: 1.3765e-13 - accuracy: 1.0000
Epoch 460/500
183/183 [==============================] - 1s 4ms/sample - loss: 6.6391e-13 - accuracy: 1.0000
Epoch 461/500
183/183 [==============================] - 1s 4ms/sample - loss: 4.8241e-15 - accuracy: 1.0000
Epoch 462/500
183/183 [==========

In [33]:
model.save('model2.h5')